### ISSUE TITLE
Changing / adding configuration in puppet.conf options doesn't work

### ISSUE THREAD

**Issue by ckaenzig** [camptocamp/puppet-puppet_conf_providers#2]
Given this initial configuration:

```
[agent]
environment = stable4
server = puppet.camptocamp.net
```

Adding e.g. a `splay` configuration gives this:

```
[agent]
environment = stable4
server = puppet.camptocamp.net
[agent]
splay = true
```

The changing the `environment` configuration gives this:

```
[agent]
environment = stable4
server = puppet.camptocamp.net
[agent]
splay = true
[agent]
environment = staging4
```

Puppet uses only the first encounter of `environment`, so it is not effectively changed an subsequent puppet run keep adding more of the last two lines above.

**Comment by mcanevet** [comment]
Wow, this is weird that when using the puppetlabs's `puppet`'s `config` face it does not generate a good configuration...

**Comment by ckaenzig** [comment]
Calling the puppet config face on the command line to change the environment value works as expected:

```
puppet config set environment staging4 --section agent
```

gives the following configuration:

```
[agent]
environment = staging4
server = puppet.camptocamp.net
[agent]
splay = true
[agent]
environment = staging4
```
